// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXBnf6m03TuAA88-ri09yvx-a3031vjDw',
    appId: '1:536761116653:web:8e4884e7b4d047dfa8a9e4',
    messagingSenderId: '536761116653',
    projectId: 'bachelorteam49',
    authDomain: 'bachelorteam49.firebaseapp.com',
    storageBucket: 'bachelorteam49.firebasestorage.app',
    measurementId: 'G-P9RRPCWJDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUux8aQ8hqzuyfP6Di7r8iWSEAx1jINv4',
    appId: '1:536761116653:android:7160081997ae3ebba8a9e4',
    messagingSenderId: '536761116653',
    projectId: 'bachelorteam49',
    storageBucket: 'bachelorteam49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX_YuabVT3CP305RB7ACycdSue17Mdokw',
    appId: '1:536761116653:ios:81c1862fbd581934a8a9e4',
    messagingSenderId: '536761116653',
    projectId: 'bachelorteam49',
    storageBucket: 'bachelorteam49.firebasestorage.app',
    iosBundleId: 'com.example.bachelor2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX_YuabVT3CP305RB7ACycdSue17Mdokw',
    appId: '1:536761116653:ios:81c1862fbd581934a8a9e4',
    messagingSenderId: '536761116653',
    projectId: 'bachelorteam49',
    storageBucket: 'bachelorteam49.firebasestorage.app',
    iosBundleId: 'com.example.bachelor2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXBnf6m03TuAA88-ri09yvx-a3031vjDw',
    appId: '1:536761116653:web:5b2b28d73d8544c4a8a9e4',
    messagingSenderId: '536761116653',
    projectId: 'bachelorteam49',
    authDomain: 'bachelorteam49.firebaseapp.com',
    storageBucket: 'bachelorteam49.firebasestorage.app',
    measurementId: 'G-XREE16H3NR',
  );
}
